
import { MarketingHeader } from "@/components/MarketingHeader";
import { PageHeader } from "@/components/PageHeader";
import { Card, CardContent } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ShieldAlert } from "lucide-react";
import Link from 'next/link';

export default function TermsOfUsePage() {
    const effectiveDate = "July 9, 2025";

    return (
        <>
            <MarketingHeader />
            <main>
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 animate-fade-in-up">
                    <PageHeader
                        title="Terms of Use"
                        description={`Last Updated: ${effectiveDate}`}
                    />
                    <Card>
                        <CardContent className="pt-6 text-foreground/90 space-y-6">
                            <p>Welcome to Shield FL (&quot;the Service&quot;). These Terms of Use (&quot;Terms&quot;) govern your access to and use of the Shield FL web application. Please read these Terms carefully before using the Service.</p>

                            <div className="space-y-2">
                                <h2 id="acceptance" className="text-xl font-semibold border-b pb-2">1. Acceptance of Terms</h2>
                                <p>By creating an account, accessing, or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and our <Link href="/privacy-policy" className="underline text-primary">Privacy Policy</Link>. If you do not agree to these Terms, you may not use the Service.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="description" className="text-xl font-semibold border-b pb-2">2. Description of Service</h2>
                                <p>Shield FL is an informational, AI-powered reference tool designed to provide active law enforcement officers with supplemental information related to Florida statutes, case law, and common law enforcement procedures. The Service is intended to aid, not replace, an officer&apos;s training and judgment.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="eligibility" className="text-xl font-semibold border-b pb-2">3. User Eligibility and Account Responsibilities</h2>
                                <p><strong>Eligibility:</strong> Use of the Service is strictly limited to verified, active law enforcement personnel. We reserve the right to verify your credentials at any time and may deny, suspend, or terminate access if eligibility cannot be confirmed or is lost.</p>
                                <p><strong>Account Security:</strong> You are solely responsible for maintaining the confidentiality of your account login credentials and for all activities that occur under your account. Account sharing is strictly prohibited.</p>
                            </div>

                            <Alert variant="destructive" className="my-6">
                                <ShieldAlert className="h-4 w-4" />
                                <AlertTitle>4. CRITICAL DISCLAIMERS AND USER ACKNOWLEDGEMENTS</AlertTitle>
                                <AlertDescription>
                                    <p className="font-bold">By using this Service, you explicitly acknowledge and agree to the following:</p>
                                    <ul className="list-disc pl-5 mt-2 space-y-2">
                                        <li><strong>Not Legal Advice:</strong> The Service does not provide legal advice. The information provided is not a substitute for legal counsel from a qualified attorney, your agency&apos;s legal advisor, or the State Attorney&apos;s Office.</li>
                                        <li><strong>For Informational Purposes Only:</strong> The Service is a supplemental reference tool. It does not replace, override, or supersede your training, experience, judgment, agency policy, directives, or direct orders. You remain solely responsible for your actions and decisions in the field.</li>
                                        <li><strong>No Warranty; Service &quot;As Is&quot;:</strong> The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without any warranties of any kind, express or implied. We do not warrant that the information provided is always accurate, complete, current, or free from errors. Laws, statutes, and case law interpretations change, and there may be delays in updating the database or the AI model&apos;s training data.</li>
                                        <li><strong>Accuracy of AI-Generated Content:</strong> You acknowledge that answers and summaries are generated by an Artificial Intelligence (AI) Large Language Model (LLM) and may contain inaccuracies, errors, or omissions. AI-generated content should be independently verified by you against official sources (e.g., Florida Statutes Online) before being relied upon for any law enforcement action.</li>
                                    </ul>
                                </AlertDescription>
                            </Alert>

                            <div className="space-y-2">
                                <h2 id="liability" className="text-xl font-semibold border-b pb-2">5. Limitation of Liability</h2>
                                <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SHIELD FL, ITS DEVELOPERS, AFFILIATES, OR PARTNERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES RESULTING FROM: (I) ANY ACTION TAKEN OR NOT TAKEN BASED ON INFORMATION FROM THE SERVICE; (II) ANY INCORRECT, INCOMPLETE, OR OUTDATED INFORMATION; (III) ANY INTERRUPTION OF SERVICE, SECURITY BREACHES, OR LOSS OF DATA; (IV) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICE.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="indemnification" className="text-xl font-semibold border-b pb-2">6. Indemnification</h2>
                                <p>You agree to indemnify, defend, and hold harmless Shield FL and its affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or in any way connected with your access to or use of the Service, or your violation of these Terms.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="jurisdiction" className="text-xl font-semibold border-b pb-2">7. Jurisdictional Limitation</h2>
                                <p>Shield FL is optimized and intended for use pursuant to the laws and statutes of the State of Florida. While the Service may be accessible in other jurisdictions, its content is not tailored for them. Use of the Service outside of Florida is at your own sole risk, and you are responsible for compliance with all applicable local laws.</p>
                            </div>
                            
                            <div className="space-y-2">
                                <h2 id="ip" className="text-xl font-semibold border-b pb-2">8. Intellectual Property</h2>
                                <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Shield FL and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="privacy" className="text-xl font-semibold border-b pb-2">9. Privacy Policy</h2>
                                <p>Our Privacy Policy, which describes how we collect, use, and share your data, is incorporated into these Terms by reference. You can review the Privacy Policy <Link href="/privacy-policy" className="underline text-primary">here</Link>.</p>
                            </div>
                            
                            <div className="space-y-2">
                                <h2 id="termination" className="text-xl font-semibold border-b pb-2">10. Termination</h2>
                                <p>We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including but not limited to a breach of these Terms.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="law" className="text-xl font-semibold border-b pb-2">11. Governing Law & Dispute Resolution</h2>
                                <p>These Terms shall be governed and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. Any legal suit, action, or proceeding arising out of or related to these Terms or the Service shall be instituted exclusively in the state or federal courts located in St. Lucie County, Florida.</p>
                            </div>

                            <div className="space-y-2">
                                <h2 id="modifications" className="text-xl font-semibold border-b pb-2">12. Modifications to Terms</h2>
                                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.</p>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </main>
        </>
    );
}
